apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.image.name }}-ingress"
  labels:
    chart: "{{ .Values.image.name }}-{{ .Chart.Version| replace "+" "_" }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Values.image.name }}-svc"
    nginx.org/websocket-services: "{{ .Values.image.name }}-svc"
spec:
  rules:
  - host: {{ .Values.service.host }}
    http:
      paths:
        {{ if eq .Values.service.path "/" }}
        - path: /
        {{ else }}
        - path: {{ .Values.service.path }}(.*)
        {{ end }}
          backend:
            serviceName: "{{ .Values.image.name }}-svc"
            servicePort: {{ .Values.service.httpPort }}
{{ if eq .Values.service.wsEnable true }}
  - host: {{ .Values.service.wsHost }}
    http:
      paths:
        - path: /ws/(.*)
          backend:
            serviceName: "{{ .Values.image.name }}-svc"
            servicePort: {{ .Values.service.wsPort }}
{{ end }}
