apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.image.name }}-svc"
  annotations:
    prometheus.io/scrape: "true"
  labels:
    chart: "{{ .Values.image.name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.wsPort }}
    targetPort: {{ .Values.service.wsPort }}
    protocol: TCP
    name: ws
  selector:
    app: "{{ .Values.image.name }}-selector"
