version: '3.6'

networks:
  example:

volumes:
  mongo:
  redis:
  nginx:


services:
  example_mongo:
    image: mongo:4
    container_name: example_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example-master
      - MONGO_INITDB_ROOT_PASSWORD=45GhtuHf50456786jBgf
    ports:
      - 27020:27017/tcp
    networks:
      - example
    volumes:
      - ./mongo/entrypoint:/docker-entrypoint-initdb.d


  example_redis:
    image: redis:5-alpine
    container_name: example_redis
    command: redis-server --requirepass 45GhtuHf50456786jBgf
    ports:
      - 6382:6379/tcp
    volumes:
      - redis:/data/cache
    networks:
      - example

  example_swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: example_swagger_ui
    environment:
      CONFIG_URL: http://local.example.com/swagger/config.json
      DISPLAY_OPERATION_ID: "true"
      DEFAULT_MODELS_EXPAND_DEPTH: 5
      DEFAULT_MODEL_EXPAND_DEPTH: 10
      SHOW_MUTATED_REQUEST: "true"
      WITH_CREDENTIALS: "true"
    networks:
      - example
    ports:
      - 8081:8080

  example_nginx:
    container_name: example_nginx
    build: nginx
    ports:
      - 80:80/tcp
    expose:
      - "80"
    networks:
      - example

  example_verdaccio:
    image: verdaccio/verdaccio:4
    environment:
      VERDACCIO_USER_NAME: example
    networks:
      - example
    ports:
      - 4874:4873

  example_ganachecli:
    build: ganachecli
    networks:
      - example
    ports:
      - 8545:8545
