apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.service.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: "{{ .Chart.Name }}-svc"
            servicePort: {{ .Values.service.httpPort }}
